apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--context=git://github.com/swathi-zelarsoft/node-hello",
            "--destination=swathipottabathini/kaniko"] 
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
