apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - image: swathipottabathini/simple
        name: node-js
        ports:
        - containerPort: 80

